version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 10080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
  php:
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker_db_user
      MYSQL_PASSWORD: docker_db_user_pass
      TZ: Asia/Tokyo
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/data:/var/lib/mysql
